site_name: My Docs
repo_url: https://github.com/neildillamore/mydocs.github.io/
theme:
  name: material
  features:
    - navigation.instant
nav:
  - Home: index.md
  - 'Contributing':
      - 'Contributing to the Standards': contributing.md
      - 'Template to Follow': template.md
  - 'Ways of Working':
      - 'Reuse': wow/reuse.md
  - About: about.md